### ISSUE TITLE
Size displayed 0kb for users with write permission to subfolder

### ISSUE THREAD

**Issue by AJHoeh** [nextcloud/groupfolders#1069]
Hey there,

I am using nextcloud 17.0.9 with groupfolders 5.0.8. 
The cloud contains only groupfolders which contain another level of groupfolders in most cases. All users have read permissions for all (sub)folders, but only users of specific groups have write permissions for specific folders. In every case only "leaf folders" are writeable.

**Problem:** In the folder overview some folders appear to be of size 0kb when in fact they are not. 
**Weird thing:** For different users different folders are hit. 
**After further investigation:** Its always folders containing subfolders and always those, which contain subfolders the user has write permission for. The size of the subfolders themselves on the other hand is displayed correctly for all users.

**Edit:** For better understanding a visual comparisson of three users. User **A** has **no write permissions** at all, User **B** has write permissions for **subfolders of folder 7** only and user **C** has write permission for **subfolders of folder 5, 6, 7, 8 and 13**. User **A** acts as a benchmark for which all folder sizes are displayed correctly.
![comparisson](https://user-images.githubusercontent.com/44893009/95438877-302d1e00-0957-11eb-8a49-f17e329b440f.png)
Permissions are solely managed via /settings/groupfolder, **no** advanced permissions are used.

I dont have expertise here but my guess is this can hardly be setup dependant and seems to be a bug?

Best
Johannes

**Comment by AJHoeh** [comment]
Maybe in some way related to #875

**Comment by orandev** [comment]
Hello,
Same issue here with Nextcloud 19.0.2 and GroupFolders 7.1.0 and S3 storage.
All users on the group folder have read/write/share access and they all see 0 KB size for folders that contain subfolders.

**Comment by artonge** [comment]
Hello,

Can you try to set the following option in `config.php` ?
```php
'quota_include_external_storage' => false
```

**Comment by CarlSchwan** [comment]
@orandev the issue with s3 storage + groupfolder size calculation has been fixed a few months ago. I don't remember seeing this sort of bugs anymore since then, but I will still try to reproduce this locally on master tomorrow

**Comment by orandev** [comment]
Hello
My last message was for version 7.1.0.
I've just tested with 7.1.3 and problem is still there.
With 10.0.0 it seems gone, but I'll confirm when I update my prod instance with 10.0.0 (in a few weeks).

**Comment by orandev** [comment]
Hello
I forgot to confirm in 2021.
I don't have the issue anymore.
