### ISSUE TITLE
can´t add group to folder

### ISSUE THREAD

**Issue by ahmed10pan** [nextcloud/groupfolders#135]
please help
option where i add group on each folder desapear.
i have some folder with already ggroup asigned but this option desapear and i can´t add to new or existing folder any group.

**Comment by puzich** [comment]
I have the same issue with a new installed nextcloud. I can't add a group(s) to the new created group folders.

**Comment by pubmania** [comment]
same here... GroupFolders version 1.2.1
![firefox_2018-07-03_12-08-48](https://user-images.githubusercontent.com/1966557/42216601-3f646b5a-7eba-11e8-93a9-4b7bcb8b9f3c.png)

**Comment by puzich** [comment]
#133 Found the same issue with more discussion here

**Comment by Cracky5457** [comment]
Same here since the update of the extension. You still can add them with the API for the moment

**Comment by tomastd** [comment]
+1

**Comment by pubmania** [comment]
>Same here since the update of the extension. You still can add them with the API for the moment

Please can you give some guidance on how to do that using the API?

**Comment by icewind1991** [comment]
Fixed with 1.2.2

**Comment by Adambean** [comment]
This still happens on OC 15.0.7 with Group Folders 2.0.4.

![image](https://user-images.githubusercontent.com/1108717/57321579-8ca06400-70f9-11e9-96cb-373051fdadac.png)

Unsure if related, but all our groups come from LDAP. (That shouldn't matter.)
