### ISSUE TITLE
Unexpected behavior when creating a group folder with the same name as an existing user folder.

### ISSUE THREAD

**Issue by dan-nkl** [nextcloud/groupfolders#18]
Version: latest master...?

1. Create folder with content and subfolders
2. Make the folder to a groupfolder
3. ???
4. Content gone!

The content of the folder should be moved into the "created" groupfolder.

**Comment by jospoortvliet** [comment]
How did you do step 2? Or is this a feature request, that an admin can turn a folder into a group folder?

**Comment by jospoortvliet** [comment]
There's a weird overlap with existing folders. Take this scenario:

* Go to the Files app and create a folder named `superawesometest`
* Put a few files in it.
* Go to the Group Folders admin and create a folder named `superawesometest`
* Add the Admin group to the access rights for `superawesometest`
* Go back to Files and observe the new Group Folder has overwritten the existing `superawesometest` and it is empty. Where are my files?!!?!
* Go to the Group Folders admin and remove Admin group access to the folder `superawesometest`
* Go back to Files and observe the new Group Folder has disappeared and the existing `superawesometest` is back with its original content!
* Note that this overwriting of existing folders with (empty) Group Folders also happens with users - if you create a group folder with the same name as a folder one of your users has, they will lose access to that folder and all its content.

I think Group Folders should act like shares - if somebody shares a folder with the same name as an existing one with you, it should show up besides the existing one, not overwrite it.

**Comment by heldchen** [comment]
ran into this issue as well, but had an additional side effect of ending up with multiple shared folderswith the same name

1. create normal folder, share with group
2. create group folder with same name

- users now see *two* shared folders
- deleting the Shared Folder results in an error, share not removed
- deleting the Group Folder removes all content but restores the Shared Folder

the workaround for the duplicated shares is to first save the folder contents, remove the Group Folder, then remove the Shared Folder, then recreate the Group Folder.

**Comment by icewind1991** [comment]
the problem with trying to do any kind of conflict resolution on creating group folders (whether it is moving the files into the group folder, or even just showing a warning), is that it would have to check for conflicts for every user that has the folder which is much to expensive to do on large instances.

**Comment by wiswedel** [comment]
Fixed by #523

**Comment by kesselb** [comment]
@wiswedel should we reopen? #523 has been reverted.

**Comment by wiswedel** [comment]
> @wiswedel should we reopen? #523 has been reverted.

totally I guess :-(

**Comment by wiswedel** [comment]
ref: https://github.com/nextcloud/groupfolders/pull/647

**Comment by fschrempf** [comment]
As far as I can see this is also covered by #648 and others and it should be finally fixed now by #1239.

**Comment by KodoGit** [comment]
The problem still exists with NC 21.0.4 docker (nextcloud:21-apache) with GF 9.0.3
Just updated from 20.

**Comment by mkaag** [comment]
Same issue with v29.0.4.1 : rename an existing "group folder" after the name of an existing fodler shared by individual account.
