### ISSUE TITLE
[Bug]: TypeError OCA\GroupFolders\Versions\GroupVersion::__construct(): Argument #11

### ISSUE THREAD

**Issue by polhenarejos** [nextcloud/groupfolders#2915]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. It is a background job. I do nothing.
2.
3.

### Expected behaviour
Not getting any error.

### Actual behaviour
I get a repetitive error in the Log section:

```
TypeError
OCA\GroupFolders\Versions\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\Files\File, OC\Files\Node\Folder given, called in /home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 159
Error while running background job (class: OCA\GroupFolders\BackgroundJob\ExpireGroupVersions, arguments: )
```

### Server configuration

**Operating system:** Debian 11

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 8.1

**Nextcloud version:** (see Nextcloud admin page) 28.0.4

**Group folders version:** 16.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded

**Where did you install Nextcloud from:** zip from web

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:**  no

### Client configuration
**Browser:** chrome 

**Operating system:** windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"0q32N4PeWVoJ7iGBlT56","level":3,"time":"2024-04-09T10:05:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )","userAgent":"--","version":"28.0.4.1","exception":{"Exception":"TypeError","Message":"OCA\\GroupFolders\\Versions\\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 159","Code":0,"Trace":[{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":159,"function":"__construct","class":"OCA\\GroupFolders\\Versions\\GroupVersion","type":"->"},{"function":"OCA\\GroupFolders\\Versions\\{closure}","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":143,"function":"array_map"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":80,"function":"getVersionsForFileFromDB","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":81,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":60,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/home/phenarejos/CASTLE/django/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersion.php","Line":33,"message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )","exception":{},"CustomMessage":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )"}}
```

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by polhenarejos** [comment]
I get this error every 1 hour and 5 minutes exactly. It's really annoying.

**Comment by nonofr91** [comment]
j'ai le même type de message dans le journal d'administration:
{"reqId":"hCZmk0MgMtg323IHuLqq","level":3,"time":"2024-05-15T19:20:01+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 32927, arguments: null)","userAgent":"--","version":"29.0.0.19","exception":{"Exception":"TypeError","Message":"OCA\\Files_Versions\\Versions\\Version::__construct(): Argument #10 ($metadata) must be of type array, string given, called in /config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersion.php on line 47","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersion.php","line":47,"function":"__construct","class":"OCA\\Files_Versions\\Versions\\Version","type":"->"},{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":158,"function":"__construct","class":"OCA\\GroupFolders\\Versions\\GroupVersion","type":"->"},{"function":"OCA\\GroupFolders\\Versions\\{closure}","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":142,"function":"array_map"},{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":80,"function":"getVersionsForFileFromDB","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":81,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":60,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/config/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/app/www/public/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/app/www/public/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/app/www/public/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/app/www/public/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/config/www/nextcloud/apps/files_versions/lib/Versions/Version.php","Line":32,"message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 32927, arguments: null)","exception":[],"CustomMessage":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 32927, arguments: null)"},"id":"6645135caef0b"}

Moi aussi cela se produit toutes les 1H05.

**Comment by masterdot** [comment]
Same here, fresh install of aio v 29

<img width="1216" alt="Bildschirmfoto 2024-05-21 um 12 30 53" src="https://github.com/nextcloud/groupfolders/assets/493105/6fa8d95a-ecc0-43e1-b382-a46391e96f05">
<img width="1204" alt="Bildschirmfoto 2024-05-21 um 12 31 06" src="https://github.com/nextcloud/groupfolders/assets/493105/9893089c-f791-48e6-b03f-5a944a0f8b9b">

**Comment by nomiskraw** [comment]
Same problem here, fresh install Nextcloud 29.0 and GroupFolder 17.0


![image](https://github.com/nextcloud/groupfolders/assets/99745097/9aa412df-69e6-4ba9-a4c4-766af887424a)

**Comment by polhenarejos** [comment]
Upgraded to 29.0.1 and still happens but the error is another

```
TypeError
OCA\GroupFolders\Versions\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given, called in /home/phenarejos/CASTLE/django/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92
Error while running background job OCA\GroupFolders\BackgroundJob\ExpireGroupVersions (id: 38, arguments: null)
```

**Comment by masterdot** [comment]
Now something did crash my cloud, I'll check tomorrow... Really starting to dislike nextcloud :/

**Comment by Markoise** [comment]
Same thing on Nextcloud 29.0.2
This is spamming my Log several times a day.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/groupfolders/pull/3022

**Comment by joshtrichards** [comment]
Fixed in #3023

**Comment by rowanmoul** [comment]
I can open an new issue if needed but I still get this error in my logs every hour here in February 2025. I'm running the latest nextcloud via nextcloud-aio and all my containers are up to date. Group Folders shows version 18.0.9 on the apps page.

```
TypeError
OCA\GroupFolders\Versions\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\Files\File, OC\Files\Node\Folder given, called in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 170
Error while running background job OCA\GroupFolders\BackgroundJob\ExpireGroupVersions (id: 90, arguments: null)
```

**Comment by joshtrichards** [comment]
@rowanmoul Can you provide the entire raw log entry (stack trace)? Looking closer at the other reports in this Issue, I can now see there are several distinct issues. 

Unfortunately many lack stack traces. I think the associated PR only addressed one of the matters.

I think there's still a problem here:

https://github.com/nextcloud/groupfolders/blob/65ba084a90689ac86172250f3e20fbb27c051b87/lib/Versions/VersionsBackend.php#L153-L160

@nonofr91 Your issue looks unrelated to this Issue. Please create a dedicated Issue for it if you're still experiencing it.

**Comment by rowanmoul** [comment]
> [@rowanmoul](https://github.com/rowanmoul) Can you provide the entire raw log entry (stack trace)?
Here is the most recent log. It doesn't look like there is anything personally sensitive in here. Let me know if I can provide anything else.
```json
{
  "reqId": "v1NwywIEMjF9ovqxaQaY",
  "level": 3,
  "time": "2025-02-11T00:36:15+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 90, arguments: null)",
  "userAgent": "--",
  "version": "30.0.5.1",
  "exception": {
    "Exception": "TypeError",
    "Message": "OCA\\GroupFolders\\Versions\\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\\Files\\File, OC\\Files\\Node\\Folder given, called in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 170",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 170,
        "function": "__construct",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersion",
        "type": "->",
        "args": [
          1710673346,
          1710673346,
          "2018",
          18632198175,
          "httpd/unix-directory",
          "2018",
          {
            "__class__": "OC\\Files\\FileInfo"
          },
          {
            "__class__": "OCA\\GroupFolders\\Versions\\VersionsBackend"
          },
          {
            "__class__": "OC\\User\\User"
          },
          [],
          {
            "__class__": "OC\\Files\\Node\\Folder"
          },
          1
        ]
      },
      {
        "function": "OCA\\GroupFolders\\Versions\\{closure}",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 150,
        "function": "array_map",
        "args": [
          {
            "__class__": "Closure"
          },
          [
            "*** sensitive parameters replaced ***"
          ]
        ]
      },
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 90,
        "function": "getVersionsForFileFromDB",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Files\\FileInfo"
          },
          {
            "__class__": "OC\\User\\User"
          }
        ]
      },
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 76,
        "function": "getVersionsForFile",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          },
          {
            "__class__": "OC\\Files\\FileInfo"
          }
        ]
      },
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 55,
        "function": "expireFolder",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": [
          {
            "0": "And 1 more entries, set log level to debug to see all entries",
            "id": 1,
            "mount_point": "Family Photo Library",
            "groups": {
              "Family": {
                "displayName": "Family",
                "permissions": 31,
                "type": "group"
              }
            },
            "quota": -3,
            "size": 0
          }
        ]
      },
      {
        "file": "/var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
        "line": 73,
        "function": "expireFolders",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": [
          [
            {
              "0": "And 1 more entries, set log level to debug to see all entries",
              "id": 1,
              "mount_point": "Family Photo Library",
              "groups": {
                "Family": {
                  "displayName": "Family",
                  "permissions": 31,
                  "type": "group"
                }
              },
              "quota": -3,
              "size": 0
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 61,
        "function": "run",
        "class": "OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 88,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 75,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 162,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          }
        ]
      }
    ],
    "File": "/var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersion.php",
    "Line": 18,
    "message": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 90, arguments: null)",
    "exception": [],
    "CustomMessage": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 90, arguments: null)"
  },
  "id": "67aaa53285c07"
}
```

**Comment by D34DC3N73R** [comment]
I get this error when running 
`docker exec -it nextcloud occ groupfolders:expire`


```
Expiring version in 'group_folder_name'
Expiring version 1694199656 for ...
...
An unhandled exception has been thrown:
TypeError: OCA\GroupFolders\Versions\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\Files\File, OC\Files\Node\Folder given, called in /config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 170 and defined in /config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersion.php:18
Stack trace:
#0 /config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php(170): OCA\GroupFolders\Versions\GroupVersion->__construct()
#1 [internal function]: OCA\GroupFolders\Versions\VersionsBackend->OCA\GroupFolders\Versions\{closure}()
#2 /config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php(149): array_map()
#3 /config/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php(88): OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFileFromDB()
#4 /config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
#5 /config/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(39): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
#6 /config/www/nextcloud/apps/groupfolders/lib/Command/ExpireGroup/ExpireGroupVersions.php(51): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#7 /config/www/nextcloud/apps/groupfolders/lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php(36): OCA\GroupFolders\Command\ExpireGroup\ExpireGroupVersions->execute()
#8 /app/www/public/3rdparty/symfony/console/Command/Command.php(326): OCA\GroupFolders\Command\ExpireGroup\ExpireGroupVersionsTrash->execute()
#9 /app/www/public/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run()
#10 /app/www/public/3rdparty/symfony/console/Application.php(1078): OC\Core\Command\Base->run()
#11 /app/www/public/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#12 /app/www/public/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#13 /app/www/public/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#14 /app/www/public/console.php(87): OC\Console\Application->run()
#15 /app/www/public/occ(33): require_once('...')
```

```
docker exec -it nextcloud occ status
  - installed: true
  - version: 31.0.2.1
  - versionstring: 31.0.2
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false

docker exec -it nextcloud occ app:list | grep groupfolders
  - groupfolders: 19.0.4
```

**Comment by D34DC3N73R** [comment]
I figured out a workaround for this issue. I believe an old version of group folders may have added folders to the db where only files should have been added. First off, backup both your database and data before proceeding, as we'll be making some manual database edits and deleting problem content.

I ran this on the db, which gave me the path of the problem directory.
`SELECT v.id, v.file_id, v.timestamp, v.size, v.mimetype, v.metadata, f.path, f.name FROM oc_group_folders_versions v JOIN oc_filecache f ON v.file_id = f.fileid WHERE f.mimetype = (SELECT id FROM oc_mimetypes WHERE mimetype = 'httpd/unix-directory') LIMIT 10;`

I copied the content out of that folder, deleted the content and folder itself, and then added the content back under a slightly different folder name. 

I'm not sure if this was needed, but I deleted the id from the trash as well
`DELETE FROM oc_filecache WHERE fileid = 1956222;`
where 1956222 was the "file id" of the deleted folder.

After that, I couldn't find the deleted folder in the trash UI, the database, or the __groupfolders/trash/ directories. 

Then I ran 
`docker exec -it nextcloud occ groupfolders:expire`
and it continued to run without error. 
I noticed the line `Cleaning up versions for no longer existing file with id 1956222` confirming the problem ID was removed. The command took a while since this was the first time in 3 years the command had run successfully. 

Hopefully, this helps someone else who is sick of that error filling up their logs.

**Comment by rowanmoul** [comment]
> I believe an old version of group folders may have added folders to the db where only files should have been added.

This gave me a clue as to what the problem was for me. Once upon a time, I re-installed my nextcloud (new database), but I didn't want to copy and paste into the new data directory as it was a lot of data (over 1 tb) so I started with a blank data dir, created the same users and group folders as before, ensuring the group folder ID was the same, and then I changed the mount point for the data dir  to my old data directory and ran an `occ scan --all` or whatever the command is to re-scan the file system. I'm pretty sure I also ran `occ groupfolders:scan` but I may not have. Either way, this clearly left groupfolders in an incorrect state in the database.

I ran your first query and it identified two folders, so I created new ones with the same name plus `-new`, *moved* all the contents to these new folders, deleted the old ones (permanently via deleted files), and then renamed the new folders to remove `-new`. I did **all** of this from the nextcloud UI, as I didn't want to do any writes directly to the database and make a further mess. I then ran `occ groupfolders:expire` and it errored out on a different folder, so I performed the same process on that one too. I looped through this for basically every folder and then it started complaining about subfolders. At that point, I just *moved* all the data out of the group folder to a temporary location within my own folders, and then *moved* all the data back. This seems to have cleared out the bad data for me.

**Comment by rowanmoul** [comment]
@provokateurin I know, that's why I didn't?
The only query I ran was the select statement (read only) that identified problem directories. Everything else I did was through the NextCloud UI.
In any case, I no longer get any errors in my logs and running expire also completes without error.

**Comment by provokateurin** [comment]
Hi, I just created https://github.com/nextcloud/groupfolders/pull/4331 which should fix this. Please give it a try and let me know if this fixes the problem.
