### ISSUE TITLE
Groupfolder 20.1.0 migration fails and leaves instances in an unusable state

### ISSUE THREAD

**Issue by nursoda** [nextcloud/groupfolders#4037]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update groupfolders from 20.0.1 to 20.1.0

### Actual behaviour

`occ app:update --all`

```
groupfolders new version available: 20.1.0
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Folder\FolderDefinition::__construct(), 6 passed in PATH/apps/groupfolders/lib/Folder/FolderManager.php on line 552 and exactly 7 expected in PATH/apps/groupfolders/lib/Folder/FolderDefinition.php:12
Stack trace:
#0 PATH/apps/groupfolders/lib/Folder/FolderManager.php(552): OCA\GroupFolders\Folder\FolderDefinition->__construct()
#1 PATH/apps/groupfolders/lib/Folder/FolderManager.php(87): OCA\GroupFolders\Folder\FolderManager->rowToFolder()
#2 PATH/apps/groupfolders/lib/Migration/WrongDefaultQuotaRepairStep.php(32): OCA\GroupFolders\Folder\FolderManager->getAllFolders()
#3 PATH/lib/private/Repair.php(107): OCA\GroupFolders\Migration\WrongDefaultQuotaRepairStep->run()
#4 PATH/lib/private/legacy/OC_App.php(574): OC\Repair->run()
#5 PATH/lib/private/App/AppManager.php(1059): OC_App::executeRepairSteps()
#6 PATH/lib/private/Installer.php(111): OC\App\AppManager->upgradeApp()
#7 PATH/core/Command/App/Update.php(88): OC\Installer->updateAppstoreApp()
#8 PATH/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\App\Update->execute()
#9 PATH/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#10 PATH/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#11 PATH/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#12 PATH/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#13 PATH/console.php(90): OC\Console\Application->run()
#14 PATH/occ(33): require_once('...')
#15 {main}Setting log level to debug

```
`occ maintenance:mode --off`
`occ upgrade`

```
An unhandled exception has been thrown:
TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in PATH/apps/groupfolders/lib/Folder/FolderManager.php:553
Stack trace:
#0 PATH/apps/groupfolders/lib/Folder/FolderManager.php(553): json_decode()
#1 PATH/apps/groupfolders/lib/Folder/FolderManager.php(87): OCA\GroupFolders\Folder\FolderManager->rowToFolder()
#2 PATH/apps/groupfolders/lib/Migration/WrongDefaultQuotaRepairStep.php(32): OCA\GroupFolders\Folder\FolderManager->getAllFolders()
#3 PATH/lib/private/Repair.php(107): OCA\GroupFolders\Migration\WrongDefaultQuotaRepairStep->run()
#4 PATH/lib/private/legacy/OC_App.php(574): OC\Repair->run()
#5 PATH/lib/private/App/AppManager.php(1059): OC_App::executeRepairSteps()
#6 PATH/lib/private/Updater.php(323): OC\App\AppManager->upgradeApp()
#7 PATH/lib/private/Updater.php(236): OC\Updater->doAppUpgrade()
#8 PATH/lib/private/Updater.php(100): OC\Updater->doUpgrade()
#9 PATH/core/Command/Upgrade.php(193): OC\Updater->upgrade()
#10 PATH/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\Upgrade->execute()
#11 PATH/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#12 PATH/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 PATH/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#14 PATH/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#15 PATH/console.php(90): OC\Console\Application->run()
#16 PATH/occ(33): require_once('...')
#17 {main}
```

### Server configuration
Arch Linux, NGINX/PHP-FPM 8.4/ACPu, Valkey, Mariadb
Nextcloud version: 32.0.0.13
Team folders version: 20.1.0

**Comment by EnderArchery** [comment]
I have the same issue.
Although I did manage to upgrade with the app disabled.  
(This was before the latest update was available and the enabled app caused error messages on the upgraded version)

BUT! I... now can't enable it anymore with the exact same error.

So my users cannot access these folders.


```
An unhandled exception has been thrown:
TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /mnt/md0/webroot/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php:553
Stack trace:
#0 /mnt/md0/webroot/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php(553): json_decode()
#1 /mnt/md0/webroot/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php(87): OCA\GroupFolders\Folder\FolderManager->rowToFolder()
#2 /mnt/md0/webroot/nextcloud/apps/groupfolders/lib/Migration/WrongDefaultQuotaRepairStep.php(32): OCA\GroupFolders\Folder\FolderManager->getAllFolders()
#3 /mnt/md0/webroot/nextcloud/lib/private/Repair.php(107): OCA\GroupFolders\Migration\WrongDefaultQuotaRepairStep->run()
#4 /mnt/md0/webroot/nextcloud/lib/private/legacy/OC_App.php(574): OC\Repair->run()
#5 /mnt/md0/webroot/nextcloud/lib/private/Installer.php(548): OC_App::executeRepairSteps()
#6 /mnt/md0/webroot/nextcloud/lib/private/Installer.php(93): OC\Installer->installAppLastSteps()
#7 /mnt/md0/webroot/nextcloud/core/Command/App/Enable.php(91): OC\Installer->installApp()
#8 /mnt/md0/webroot/nextcloud/core/Command/App/Enable.php(64): OC\Core\Command\App\Enable->enableApp()
#9 /mnt/md0/webroot/nextcloud/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\App\Enable->execute()
#10 /mnt/md0/webroot/nextcloud/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#11 /mnt/md0/webroot/nextcloud/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#12 /mnt/md0/webroot/nextcloud/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#13 /mnt/md0/webroot/nextcloud/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#14 /mnt/md0/webroot/nextcloud/console.php(90): OC\Console\Application->run()
#15 /mnt/md0/webroot/nextcloud/occ(33): require_once('...')
#16 {main}                                                                              
```

**Comment by nursoda** [comment]
My workaround is a dirty downgrade. Assumptions/prerequisites:
  - instance is in maintenance mode
  - groupfolder was 20.0.1 before (if not, download the version you had before and adapt deletions in oc_migration)

Steps
- backup/dump table oc_migrations of the CLOUD DB
- `delete from oc_migrations where version = '2000002Date20250927142943';`
- move aside CLOUD/apps/groupfolders
- download and unpack https://github.com/nextcloud-releases/groupfolders/releases/download/v20.0.1/groupfolders-v20.0.1.tar.gz to CLOUD/apps
- `occ maintenance:mode --off`
- `occ upgrade` (should not be necessary if only groupfolders was upgraded and re-downgraded)

**Comment by small1** [comment]
One easy solution is to update the oc_group_folders table and set options to "" instead of null

update oc_group_folders set options="";

run occ upgrade
disable maintenance mode

That will solve it.

**Comment by come-nc** [comment]
Somehow the upgrade command gets incompatible versions of the classes from groupfolders, one from before upgrade and one from after :-/

**Comment by small1** [comment]
@come-nc can the options table be blank instead of NULL?   (as i fixed my instances that broke)

**Comment by MichaIng** [comment]
Yes, this one is missing in the trace: https://github.com/nextcloud/groupfolders/commit/189fc98

Oh, the commit is not in v20.1.0 tag, or am I blind?

**Comment by come-nc** [comment]
https://github.com/nextcloud/groupfolders/pull/4011 is missing on stable32

**Comment by DaanSelen** [comment]
I managed to get this working when editing the `/config/www/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php`

And specifically set this on line 553:
```
         private function rowToFolder(array $row): FolderDefinition {
                 $options = ""; //json_decode($row['options'], true);
                 return new FolderDefinition(
```

But I am afraid this will be overwritten on a following update.

**Comment by nursoda** [comment]
In software development it's human to miss a tag or overlook an edge case. But this (kind of) error would have been easily spotted if someone would have manually tested it by upgrading from any older version. API errors ("expecting N arguments but only got N-1" or "expecting type X but got NULL") can and should be noticed prior to releasing an app. Please either do manual tests (upgrades in this case) or enhance your CI pipeline accordingly (which is hard to set up in a way that all edge cases are included).

**Comment by MichaIng** [comment]
@DaanSelen 
Note that your folder options will then always be empty, which might break related features.

Test this if you find time: https://github.com/nextcloud/groupfolders/pull/4038

@nursoda 
Jep, I will test with 20.0.1 => 20.1.0 + above commit when home if not released yet. But the more the better, so this time all works well, after the previous release had the migration issue already.

**Comment by nursoda** [comment]
Thanks for the quick fix, @MichaIng. Since the broken 2.1.0 is still available in the app store, will you pull it or release an update superseeding 20.1.0 soon? Also, two workarounds are described here. Will either of them thwart upgrading to the fixed release (20.1.1?)?

**Comment by st31ny** [comment]
I succeeded to activate the app by backporting #4011 , however, now I only see group folders in the admin view but they are gone for all users. So, there might even be another issue.

**Comment by slu-010101** [comment]
I guess it's not a good idea to change values in the database, the problem getting bigger and bigger.

**Comment by come-nc** [comment]
So, #4038 will fix the second issue (`TypeError: json_decode(): Argument #1 ($json) must be of type string`), but the first one, `ArgumentCountError: Too few arguments to function OCA\GroupFolders\Folder\FolderDefinition::__construct()` is caused by the way server is upgrading apps and is harder to fix.

Luckily it will only crash once, so if you run upgrade again it should work.

This is not something we can test before releasing easily, because it only happens when downloading the code from the appstore. It happens when the PHP classes in memory differs from the ones on the disk.
We are looking into how to fix that on server side but it is not easy.

**Comment by slu-010101** [comment]
@come-nc will there be a new app version before or after the second fix with the PHP classes?

**Comment by MichaIng** [comment]
@nursoda 
Neither my fix nor my app, just encouraging people to test the fix that was in master already instead of custom ones or database hacks.

@come-nc 
Might the somewhat recently added OPcache reset on app updates be related, if it is done at the wrong place, or if there is some sort or parallelization => race condition between OPcache reset and app migrations? https://github.com/nextcloud/server/pull/53210
It's aim was to actually solve such sort of issues (symptom-wise), where natural OPcache invalidation might come too late or one updated script might have been invalidated while the other one was not yet. But it would need to be assured that the whole app and all its classes are freshly loaded after the update/OPcache reset.

> This is not something we can test before releasing easily

Do a pre-release, those which are only offered when on beta channel. Until I fall asleep, as tired as I am back home from the conference, I can test such ASAP.

**Comment by solracsf** [comment]
> Do a pre-release, those which are only offered when on beta channel.

Second this. Since this is app is somewhat critical, beta/RCs releases make sense here 👍

**Comment by come-nc** [comment]
@MichaIng The opcache_reset takes care of the opcache but not of memory. So it’s not enough. I do not have a clean solution yet.

**Comment by Ramalama2** [comment]
i fixed it by:
```
ALTER TABLE oc_group_folders ADD permissions VARCHAR(255) DEFAULT '{}';
UPDATE oc_group_folders SET options = '{}' WHERE options IS NULL;
```

and it worked now. just for everyone else, as help.

**Comment by EnderArchery** [comment]
> i fixed it by: ALTER TABLE oc_group_folders ADD permissions VARCHAR(255) DEFAULT '{}'; UPDATE oc_group_folders SET options = '{}' WHERE options IS NULL;
> 
> and it worked now. just for everyone else, as help.

Permissions is missing too? That's good to know.  
I guess making the options field not NULLable should also change? (although... "" would probably break similarly)...
it still doesn't explain why the migration code that's supposed to do this stuff fails...

**Comment by DaanSelen** [comment]
> [@DaanSelen](https://github.com/DaanSelen) Note that your folder options will then always be empty, which might break related features.
> 
> Test this if you find time: [#4038](https://github.com/nextcloud/groupfolders/pull/4038)
> 
> [@nursoda](https://github.com/nursoda) Jep, I will test with 20.0.1 => 20.1.0 + above commit when home if not released yet. But the more the better, so this time all works well, after the previous release had the migration issue already.

Thank you for the heads up. I looked at the PR and just changed the lines that will come up once that is released!
Hopefully everyone manages to fix this.

**Comment by dakky** [comment]
hmm i guess i got hit by this too. Th eproblem is: i can't even run occ commands to update/disable the app. I always get the error:
```
www-data@d7a98e914cfd:~/html$ ./occ app:update
PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
```

Any idea how to get out of this and get my instance up again? Is extracting the latest archive into the filesystem a good idea?

**Comment by EnderArchery** [comment]
> hmm i guess i got hit by this too. Th eproblem is: i can't even run occ commands to update/disable the app. I always get the error:
> 
> ```
> www-data@d7a98e914cfd:~/html$ ./occ app:update
> PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
> ```
> 
> Any idea how to get out of this and get my instance up again? Is extracting the latest archive into the filesystem a good idea?

Not being able to disable the app is strange though.  
Is anyone else able to confirm that this error image belongs to the same error?  
(I assume you upgraded NextCloud after the new groupfolders version was available? I did the upgrade with the previous version installed so it just got disabled automatically)

**Comment by dakky** [comment]
unfortunetly i upgraded (automatically via docker:latest tag) NC before the groupfolders app. so basically i have a updated NC setup with an old groupfolders app. An now i get a HTTP 500 via webui of NC (at once, not when accessing something, not even a login). `occ` throws the pasted error above. so basically i have only filesystem access to my instance as webui an occ are not usable anymore

EDIT: log message when accessing the webui:
```
cloud-app-1  | xxx.xxx.xxx.xxx - - [30/Sep/2025:08:49:50 +0000] "GET / HTTP/1.1" 500 1418 "-" "Uptime-Kuma/1.23.16"
cloud-app-1  | [Tue Sep 30 08:50:50.630452 2025] [php:error] [pid 67:tid 67] [client xxx.xxx.xxx.xxx:0] PHP Fatal error:  Class OCA\\GroupFolders\\Versions\\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\\Files_Versions\\Versions\\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
```

EDIT2: stange: i have the same setup like you have, but the app seems still enabled or at least still throws an http 500

**Comment by tobiaswer** [comment]
> ```
> cloud-app-1  | xxx.xxx.xxx.xxx - - [30/Sep/2025:08:49:50 +0000] "GET / HTTP/1.1" 500 1418 "-" "Uptime-Kuma/1.23.16"
> cloud-app-1  | [Tue Sep 30 08:50:50.630452 2025] [php:error] [pid 67:tid 67] [client xxx.xxx.xxx.xxx:0] PHP Fatal error:  Class OCA\\GroupFolders\\Versions\\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\\Files_Versions\\Versions\\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
> ```

I have the same issue, I was able to get back in the Web UI by manually editing the VersionsBackend.php and adding the "getRevision"-function and then restarting.

https://github.com/nextcloud/groupfolders/blob/c65617612010947ca00fedb2554a36a4a3815f31/lib/Versions/VersionsBackend.php

It seems like this was fixed in https://github.com/nextcloud/groupfolders/pull/3885. But for some reason my Teamfolders didn't update.

**Comment by EnderArchery** [comment]
Yeah ok... your instance seems to be failing in a completely different code path.  
It might also be related to group folders... but yours does not seem to fail at the "getting group folder options" stage at all.

i.e. ... different bug?

**Comment by solracsf** [comment]
@dakky @tobiaswer can you please open a separate bug report?
Thanks 👍

**Comment by boexler** [comment]
**Before applying changes, check if the column already exists:**

```sql
DESCRIBE oc_group_folders;
```

If the permissions column is missing, add it using LONGTEXT (instead of VARCHAR(255)), since Group Folders stores JSON data that may exceed 255 characters:

```sql
ALTER TABLE oc_group_folders ADD COLUMN permissions LONGTEXT DEFAULT '{}' AFTER options;
```

## Shell MariaDB

```shell
root@d719236f4207:/# mariadb
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 20326
Server version: 11.4.4-MariaDB Alpine Linux

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use nextcloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [nextcloud]> SELECT DATABASE();
+------------+
| DATABASE() |
+------------+
| nextcloud  |
+------------+
1 row in set (0.001 sec)

MariaDB [nextcloud]> 
MariaDB [nextcloud]> DESCRIBE oc_group_folders;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| folder_id   | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| mount_point | varchar(4000) | NO   |     | NULL    |                |
| quota       | bigint(20)    | NO   |     | NULL    |                |
| acl         | int(11)       | YES  |     | 0       |                |
| root_id     | bigint(20)    | YES  |     | NULL    |                |
| storage_id  | bigint(20)    | YES  |     | NULL    |                |
| options     | longtext      | YES  |     | NULL    |                |
+-------------+---------------+------+-----+---------+----------------+
7 rows in set (0.002 sec)

MariaDB [nextcloud]> ALTER TABLE oc_group_folders ADD COLUMN permissions LONGTEXT DEFAULT '{}' AFTER options;
Query OK, 0 rows affected (0.235 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [nextcloud]> DESCRIBE oc_group_folders;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| folder_id   | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| mount_point | varchar(4000) | NO   |     | NULL    |                |
| quota       | bigint(20)    | NO   |     | NULL    |                |
| acl         | int(11)       | YES  |     | 0       |                |
| root_id     | bigint(20)    | YES  |     | NULL    |                |
| storage_id  | bigint(20)    | YES  |     | NULL    |                |
| options     | longtext      | YES  |     | NULL    |                |
| permissions | longtext      | YES  |     | '{}'    |                |
+-------------+---------------+------+-----+---------+----------------+
8 rows in set (0.004 sec)
```

## Edit
@MichaIng I mistakenly picked up something incorrectly and built on top of it.

**Comment by MichaIng** [comment]
@Ramalama2 @djonasdev Where do you guys get the idea from that a `permissions` column would be needed?

I would just patch the fix inside that has already been merged (just not yet released). A re-triggered integrity check will fail on that particular script, but IMO better than touching the database manually, at least as a general workaround recommendation for all people who lang here:

```sh
cd /path/to/nextcloud/apps/groupfolders
curl -sSf 'https://patch-diff.githubusercontent.com/raw/nextcloud/groupfolders/pull/4038.patch' | sudo -u www-data patch -p1
```
_Adjust path and webserver user accordingly._

This makes setting the `options` value to non-null obsolete, as intended. I could not find any hint of a `permissions` column in the code. Would be great if you could provide the error message you were able to fix by adding it, so we can add proper null value handling for this as well.

**Comment by small1** [comment]
Permissions should not be there. 

Correct should be:

MariaDB [nextcloud]> describe oc_group_folders;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| folder_id   | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| mount_point | varchar(4000) | NO   |     | NULL    |                |
| quota       | bigint(20)    | NO   |     | NULL    |                |
| acl         | int(11)       | YES  |     | 0       |                |
| root_id     | bigint(20)    | YES  |     | NULL    |                |
| storage_id  | bigint(20)    | YES  |     | NULL    |                |
| options     | longtext      | YES  |     | NULL    |                |
+-------------+---------------+------+-----+---------+----------------+
7 rows in set (0.002 sec)

**Comment by EnderArchery** [comment]
I can confirm that this patch seems to fix the issue entirely without manually intervening in any other way. No dirty downgrades or db edits.

My NextCloud was upgraded prior to the update to groupfolders so it was initially deactivated automatically, because it wasn't flagged for the compatibility with the new version. So my groupfolders upgrade happened after and separately from the NC instanze upgrade.  
(Just in case this information becomes useful in future troubleshooting)

I have NOT manually confirmed that my options column is set to use longtext (I also haven't touched it manually though)

**Comment by MichaIng** [comment]
> I have NOT manually confirmed that my options column is set to use longtext (I also haven't touched it manually though)

The data type should be assured to be set correctly by the app as well. People tend to copy&paste too much. If there is no hint that `permissions` is needed, and no hint that any data types or stuff needs to be changed (in certain circumstances), I suggest to hide the posts which suggest this. The two workarounds which make sense, and can be well explained from the error messages and the code:
1. Set `options` value to empty string, or the string `{}` => empty JSON object. Should not matter which one, since an empty string is evaluated like empty JSON object as well.
2. Preferred by me: apply the code change that will be part of next release, which handles the `options` null value gracefully:
    ```sh
    cd /path/to/nextcloud/apps/groupfolders
    curl -sSf 'https://patch-diff.githubusercontent.com/raw/nextcloud/groupfolders/pull/4038.patch' | sudo -u www-data patch -p1
    ```

@come-nc 
Makes sense regarding code in RAM. Naturally, this could cause a lot of potential errors if parts of the app's old code still runs/is still loaded after it has been updated, so I am confused that there is no point during the update at which the app is assured to be reloaded completely, i.e. all its classes and functions. Is there a related issue at the server repo or elsewhere you are discussion this, and probably the reason why the migration steps for 19.x => 20.x were not applied in all cases? Maybe I am on the wrong track, but I start to think that all of this might be related, possibly as a result of some parallelization/async behavior added with NC32 for performance reasons (as far as I remember the presentation). <s>Migrations seem to be skipped in other apps as well, randomly, so this does not look like a mistake in the Team Folders app, is it? https://help.nextcloud.com/t/after-update-to-nc-32-app-store-gone/233158/42?u=michaing</s> EDIT: The linked case was as of incompatible metadata app being enabled, the one below that show a weird table name, so maybe also not related to a missing migration.

**Comment by EnderArchery** [comment]
@MichaIng I agree. That's why I didn't add it \^\^

But as far as I can tell, in this case there weren't any migration steps skipped but... just wrong assumptions about the state in the DB?

But in general, if there are cases where code is skipped... opcache and timestamp validation, while upgrading via the community updater? (That's a web GUI so the cache settings for... well the web GUI probably apply?)

**Comment by nexion63** [comment]
I'm experiencing an issue on my end: I can no longer access the app stores, delete files, or create folders. I’m seeing an error message in the Nextcloud logs (see below), and on the web interface, I get notifications like “Creating new folder failed” or “Upload error: Connection refused” after attempting to upload a file.

I noticed that when I run the command 'occ app:enable groupfolders', I immediately get the message "Connection refused" right afterward.

Thank you for your help.

`{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"--","app":"serverDI","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\IServerContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"serverDI"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"--","app":"serverDI","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\IServerContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"serverDI"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"--","app":"serverDI","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\IServerContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"serverDI"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"serverDI","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\IServerContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"serverDI"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":3,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"admin_notifications","method":"GET","url":"/settings/apps","message":"/appinfo/app.php is not supported anymore, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"admin_notifications"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"dav","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\AppFramework\\IAppContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"dav"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"dav","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\AppFramework\\IAppContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"dav"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":0,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"federatedfilesharing","method":"GET","url":"/settings/apps","message":"The requested alias \"OCP\\AppFramework\\IAppContainer\" is deprecated. Please request \"Psr\\Container\\ContainerInterface\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"federatedfilesharing"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":3,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"core","method":"GET","url":"/settings/apps","message":"Could not read app info file for app \"groupfolders.BK2\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","data":{"app":"core"}}
{"reqId":"1HcIDIYMKUvixtTs4JjW","level":3,"time":"2025-09-30T16:44:24+00:00","remoteAddr":"2a01:cb0c:8aab:6500:edb1:56b8:a13:5b11","user":"Arnaud","app":"index","method":"GET","url":"/settings/apps","message":"Could not find web path for groupfolders.B","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","version":"32.0.0.13","exception":{"Exception":"OCP\\App\\AppPathNotFoundException","Message":"Could not find web path for groupfolders.B","Code":0,"Trace":[{"file":"/app/www/public/lib/private/URLGenerator.php","line":231,"function":"getAppWebPath","class":"OC\\App\\AppManager","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_App.php","line":474,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":250,"function":"listAllApps","class":"OC_App","type":"->"},{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":96,"function":"getAppsWithUpdates","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":204,"function":"viewApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":118,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":153,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":321,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/lib/base.php","line":1061,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/index.php","line":25,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/App/AppManager.php","Line":719,"message":"Could not find web path for groupfolders.B","exception":{},"CustomMessage":"Could not find web path for groupfolders.B"}}`

**Comment by come-nc** [comment]
> Makes sense regarding code in RAM. Naturally, this could cause a lot of potential errors if parts of the app's old code still runs/is still loaded after it has been updated, so I am confused that there is no point during the update at which the app is assured to be reloaded completely, i.e. all its classes and functions. Is there a related issue at the server repo or elsewhere you are discussion this, and probably the reason why the migration steps for 19.x => 20.x were not applied in all cases? Maybe I am on the wrong track, but I start to think that all of this might be related, possibly as a result of some parallelization/async behavior added with NC32 for performance reasons (as far as I remember the presentation). 

@MichaIng 
No, there is no way to ask PHP to forget about a class once it’s loaded. Only way is to start a new process. I did not find a clean solution yet.
The only place it’s causing problems is if repairsteps and migrations are calling code from the actual app. That’s not common to that’s usually not a big issue.

**Comment by ollimaz** [comment]
I'm having the same issue after updating groupfolders to 19.1.7

Thats why I would disagree with https://github.com/nextcloud/groupfolders/pull/4011#issuecomment-3346813222

But I can't really prove it because I have a managed nextcloud instance but no access to the logs but the behaviour is the same for Nextcloud 31 and the latest groupfolders update

**Comment by nursoda** [comment]
I confirm that patching 20.1.0 as proposed by @MichaIng in the [above post](https://github.com/nextcloud/groupfolders/issues/4037#issuecomment-3352521147) does fix all issues for my instances. I used these commands (for each cloud) to do so:

``` bash
sudo -i -u http
cd $yourcloudfolder
occ app:remove groupfolders          # 20.0.1
cd apps
wget https://github.com/nextcloud-releases/groupfolders/releases/download/v20.1.0/groupfolders-v20.1.0.tar.gz
tar xzf groupfolders-v20.1.0.tar.gz && rm groupfolders-v20.1.0.tar.gz
cd groupfolders
curl -sSf 'https://patch-diff.githubusercontent.com/raw/nextcloud/groupfolders/pull/4038.patch' | patch -p1
cd ../..
occ app:enable groupfolders          # 20.1.0, runs migration without error
```

**Comment by brum74** [comment]
I am running the nextcloud docker container and I am unable to apply the patch.  I connect through portainer with www-data user.  When trying to apply the patch I get:

```
patching file lib/Folder/FolderManager.php
Hunk #1 FAILED at 549.
Hunk #2 FAILED at 558.
2 out of 2 hunks FAILED -- saving rejects to file lib/Folder/FolderManager.php.rej
```

If I try to do anything with occ I get the following:

```
PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
```

**Comment by SmartByME** [comment]
You can work around this by writing a dummy method into the file.
`custom_apps/groupfolders/lib/Versions/VersionsBackend.php`

```
public function getRevision(\OC\Files\Node\Node $node): int {
    return 0;
}
```

**Comment by EnderArchery** [comment]
> I am running the nextcloud docker container and I am unable to apply the patch. I connect through portainer with www-data user. When trying to apply the patch I get:
> 
> ```
> patching file lib/Folder/FolderManager.php
> Hunk #1 FAILED at 549.
> Hunk #2 FAILED at 558.
> 2 out of 2 hunks FAILED -- saving rejects to file lib/Folder/FolderManager.php.rej
> ```
> 
> If I try to do anything with occ I get the following:
> 
> ```
> PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
> ```

Well... again though... I think you're running into a different bug than described in this issue?  
You're not running into an issue with the options retrieval code path but rather... something different.

(As a hint though... is your versions backend app up to date and enabled?)

You're patching the FolderManager.php file (where we crash) but... you crash in VersionsBackend.php

Please search or open another issue for this?

**Comment by brum74** [comment]
> > I am running the nextcloud docker container and I am unable to apply the patch. I connect through portainer with www-data user. When trying to apply the patch I get:
> > ```
> > patching file lib/Folder/FolderManager.php
> > Hunk #1 FAILED at 549.
> > Hunk #2 FAILED at 558.
> > 2 out of 2 hunks FAILED -- saving rejects to file lib/Folder/FolderManager.php.rej
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I try to do anything with occ I get the following:
> > ```
> > PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
> > ```
> 
> Well... again though... I think you're running into a different bug than described in this issue? You're not running into an issue with the options retrieval code path but rather... something different.
> 
> (As a hint though... is your versions backend app up to date and enabled?)
> 
> You're patching the FolderManager.php file (where we crash) but... you crash in VersionsBackend.php
> 
> Please search or open another issue for this?

Sorry for the posting in the wrong issue, I was in another and clicked through some linked issues and guess I forgot to go back.  The reply by @SmartByME was what I needed to get the instance running again.

**Comment by snetAT** [comment]
> I am running the nextcloud docker container and I am unable to apply the patch. I connect through portainer with www-data user. When trying to apply the patch I get:
> 
> ```
> patching file lib/Folder/FolderManager.php
> Hunk #1 FAILED at 549.
> Hunk #2 FAILED at 558.
> 2 out of 2 hunks FAILED -- saving rejects to file lib/Folder/FolderManager.php.rej
> ```
> 
> If I try to do anything with occ I get the following:
> 
> ```
> PHP Fatal error:  Class OCA\GroupFolders\Versions\VersionsBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\Files_Versions\Versions\IVersionBackend::getRevision) in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 40
> ```

First update to 20.1.0, then apply the patch.

**Comment by BJKle** [comment]
I removed group folders completely to get my NC running again. Cannot reinstall it :-(

**Comment by DaanSelen** [comment]
Something which has helped me repair a lot of Nextcloud instances stuck on groupfolders 19.x.x or with FolderManager.php - Application.php or VersionsBackend.php errors is this gist I publicized:

https://gist.github.com/DaanSelen/5e262e0f84d7e2cce70a96e200afdf8e

Make sure to check out how it works and if you encounter any errors let me know.

**Comment by DaanSelen** [comment]
> You can work around this by writing a dummy method into the file. `custom_apps/groupfolders/lib/Versions/VersionsBackend.php`
> 
> ```
> public function getRevision(\OC\Files\Node\Node $node): int {
>     return 0;
> }
> ```

This works but needs an update immediately after, replacing a non-existent function with one that does functionality nothing is not very safe!

**Comment by TueC0905** [comment]
Here my way to solve the issue:

After reinstall TeamsFolder 20.0.1 as the last working point I did the upgrade to TeamsFolder 20.1.0. The upgrade fails and with review to the post from @DaanSelen I found in

/config/www/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php at line 552 ff the following:

private function rowToFolder(array $row): FolderDefinition {
                             json_decode($row['options'], true);
                             return new FolderDefinition(

I missed the part: " $options = ""; // "

After adding these part to

private function rowToFolder(array $row): FolderDefinition {
                             $options = "";  //json_decode($row['options'], true);
                             return new FolderDefinition(

followed by do occ upgrade and restart php-fpm and nginx NC32 including TeamsFolder 20.1.0 is running correctly.

**Comment by DaanSelen** [comment]
> Here my way to solve the issue:
> 
> After reinstall TeamsFolder 20.0.1 as the last working point I did the upgrade to TeamsFolder 20.1.0. The upgrade fails and with review to the post from [@DaanSelen](https://github.com/DaanSelen) I found in
> 
> /config/www/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php at line 552 ff the following:
> 
> private function rowToFolder(array $row): FolderDefinition { json_decode($row['options'], true); return new FolderDefinition(
> 
> I missed the part: " $options = ""; // "
> 
> After adding these part to
> 
> private function rowToFolder(array $row): FolderDefinition { $options = ""; //json_decode($row['options'], true); return new FolderDefinition(
> 
> followed by do occ upgrade and restart php-fpm and nginx NC32 including TeamsFolder 20.1.0 is running correctly.

Glad to hear you fixed it!

**Comment by snetAT** [comment]
same mistake with 20.1.1

nxc app:update groupfolders

```
groupfolders new version available: 20.1.1
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Folder\FolderDefinition::__construct(), 6 passed in /var/www/html/apps/groupfolders/lib/Folder/FolderManager.php on line 552 and exactly 7 expected in /var/www/html/apps/groupfolders/lib/Folder/FolderDefinition.php:12
Stack trace:
#0 /var/www/html/apps/groupfolders/lib/Folder/FolderManager.php(552): OCA\GroupFolders\Folder\FolderDefinition->__construct()
#1 /var/www/html/apps/groupfolders/lib/Folder/FolderManager.php(87): OCA\GroupFolders\Folder\FolderManager->rowToFolder()
#2 /var/www/html/apps/groupfolders/lib/Migration/WrongDefaultQuotaRepairStep.php(32): OCA\GroupFolders\Folder\FolderManager->getAllFolders()
#3 /var/www/html/lib/private/Repair.php(107): OCA\GroupFolders\Migration\WrongDefaultQuotaRepairStep->run()
#4 /var/www/html/lib/private/legacy/OC_App.php(574): OC\Repair->run()
#5 /var/www/html/lib/private/App/AppManager.php(1059): OC_App::executeRepairSteps()
#6 /var/www/html/lib/private/Installer.php(111): OC\App\AppManager->upgradeApp()
#7 /var/www/html/core/Command/App/Update.php(88): OC\Installer->updateAppstoreApp()
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\App\Update->execute()
#9 /var/www/html/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#10 /var/www/html/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/html/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#12 /var/www/html/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#13 /var/www/html/console.php(90): OC\Console\Application->run()
#14 /var/www/html/occ(33): require_once('...')
```

**Comment by come-nc** [comment]
@snetAT this is the update issue talked about above. Should be fixed by running the upgrade again, right?

**Comment by DaanSelen** [comment]
> same mistake with 20.1.1

Have you pulled the latest code from the github?

**Comment by come-nc** [comment]
@snetAT That was upgrading from 20.1.0? That does not match, the line numbers are wrong. Do you have very agressive opcache settings or something?

**Comment by slu-010101** [comment]
How can my Nextcloud found this update?
```

root@ncsrv:~# sudo -u www-data php /var/www/nextcloud/occ app:list | grep groupfolder
 - groupfolders: 20.1.0 (installed 20.1.0)
 
root@ncsrv:~# sudo -u www-data php /var/www/nextcloud/occ app:update groupfolders
groupfolders is up-to-date or no updates could be found
```

**Comment by DaanSelen** [comment]
> How can my Nextcloud found this update?
> 
> ```
> 
> root@ncsrv:~# sudo -u www-data php /var/www/nextcloud/occ app:list | grep groupfolder
>  - groupfolders: 20.1.0 (installed 20.1.0)
>  
> root@ncsrv:~# sudo -u www-data php /var/www/nextcloud/occ app:update groupfolders
> groupfolders is up-to-date or no updates could be found
> ```

You are on the latest version. Are you still receiving the error?

**Comment by slu-010101** [comment]
> You are on the latest version.

No, if you mean groupfolder, my Nextcloud don't find the update, still on 20.1.0.
"groupfolders is up-to-date or no updates could be found"

**Comment by DaanSelen** [comment]
> > You are on the latest version.
> 
> No, if you mean groupfolder, my Nextcloud don't find the update, still on 20.1.0. "groupfolders is up-to-date or no updates could be found"

2.1.1 https://github.com/nextcloud/groupfolders/releases has been releases about 1 hour ago. So perhaps some index'es are still syncing. You can manually grab the latest code from the github.

**Comment by EnderArchery** [comment]
20.1.1 seems to install, activate and work flawlessly on my end. (Barebones install)

**Comment by snetAT** [comment]
> [@snetAT](https://github.com/snetAT) That was upgrading from 20.1.0? That does not match, the line numbers are wrong. Do you have very agressive opcache settings or something?

@come-nc
Yes, after an occ upgrade, the process ran without errors.

**Comment by MichaIng** [comment]
There are/were two dedicated issues as explained here: https://github.com/nextcloud/groupfolders/issues/4037#issuecomment-3347574545

They refer to the two respective error messages in first post:
1. Happens during first update attempt to 20.1.y only, but an `occ upgrade` should solve it. There is no point to try solving this by hacking a script or so, as it solved itself already when you run into this error. Not great that this happens in the first place, but seems to not be trivial to solve, and to me seems more like an NC core/server issue, less an issue of the app.
2. Solved in 20.1.1, hence one should never require to patch any script or database anymore.

New app versions are not seen immediately by all NC instances, so give it a day if 20.1.1 is not offered yet.

If you have any other error messages than those two from the first post, please open a new issue, as it is then unrelated.

Please keep comments here at a minimum unless you have information to add to solve the first issue. Though the devs seem on it in different channels already.

**Comment by ollimaz** [comment]
Seems that the same error occurs for [stable31] (especially v19.1.7) when can I expect a fix for older instances?

**Comment by joergmschulz** [comment]
Cheeerio, the 20.1.1 version seems to fix the issue! @nursoda you can close this issue I presume

**Comment by lukaslangrock** [comment]
Same here 20.1.0 to 20.1.1 update went fine.
When I upgraded my Nextcloud (31->32) early today, the upgrade through the web-based updater failed, so I did a manual upgrade instead and got left with the groupfolders app disabled. I then applied the `$options = ""; //json_decode(...` fix to get the app back and working, but couldn't re-run the upgrade command as it was already completed.

Are there any migrations left to run that I missed out on because of the interrupted update, or did the app-update to 20.1.1 take care of uncompleted migrations? After all, this issue got quite long now and there were a lot of comments around modifying database tables, just wanting to know if I'm missing something.

\* edit: mentioned wrong version number

**Comment by slu-010101** [comment]
20.1.1 works also for me, thank you!

**Comment by EnderArchery** [comment]
> Same here 20.1.0 to 20.1.1 update went fine. When I upgraded my Nextcloud (31->32) early today, the upgrade through the web-based updater failed, so I did a manual upgrade instead and got left with the groupfolders app disabled. I then applied the `$options = ""; //json_decode(...` fix to get the app back and working, but couldn't re-run the upgrade command as it was already completed.
> 
> Are there any migrations left to run that I missed out on because of the interrupted update, or did the app-update to 20.1.1 take care of uncompleted migrations? After all, this issue got quite long now and there were a lot of comments around modifying database tables, just wanting to know if I'm missing something.
> 
> * edit: mentioned wrong version number

The fix you applied... from the little code snipped you shared, I don't think you were running 20.1.1, but 20.1.0.  
So if you now make sure that you update the app to 20.1.1... you should be good to go.
And... no... I don't think you need to do anything after that.

**Comment by lukaslangrock** [comment]
Sorry that might have been written poorly, I meant when I upgraded nc from 31 to 32, the version I got for groupfolders was the release from 2 days ago, 20.1.0 I think. That resulted in an interuppted nc upgrade process with the groupfolders app unable to be activated. This required the fix in the php code to get it working again, but at that point the instance was already out of the upgrade process, thus running `occ upgrade` didn't seem to do anything.

So my question is, after now updating to the today released 20.1.1, are there any unfinnished migrations in regards to this app that still need to manually invoked, or is installing this update sufficient?

**Comment by EnderArchery** [comment]
> Sorry that might have been written poorly, I meant when I upgraded nc from 31 to 32, the version I got for groupfolders was the release from 2 days ago, 20.1.0 I think. That resulted in an interuppted nc upgrade process with the groupfolders app unable to be activated. This required the fix in the php code to get it working again, but at that point the instance was already out of the upgrade process, thus running `occ upgrade` didn't seem to do anything.
> 
> So my question is, after now updating to the today released 20.1.1, are there any unfinnished migrations in regards to this app that still need to manually invoked, or is installing this update sufficient?

Yes, it is sufficient, as described by my previous comment in which I have confirmed the bug having been fixed by the proper patch being applied to my file^^

**Comment by lukaslangrock** [comment]
Thank you ^^

**Comment by nursoda** [comment]
Confirming that "occ app:update -all" on an 2.1.0+patch doesn't break it either. This closing. Thanks to all!
@come-nc You might want to remove Label "4. to release" as cleanup. I can't.
