### ISSUE TITLE
Nextcloud 16: Can't open files in OnlyOffice

### ISSUE THREAD

**Issue by puzich** [nextcloud/groupfolders#411]
Since the update to nextcloud 16, I also updated all Apps. But since then, I can't open any files, which are in a group folder, in OnlyOffice anymore. I get the error message "Download failed". 

Within the protocol, I found this error: 
`{"reqId":"f5irRxZRaJ3WIIF3tDjy","level":3,"time":"2019-05-02T08:47:50+00:00","remoteAddr":"91.50.227.209","user":"--","app":"index","method":"GET","url":"/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjg1NCwidXNlcklkIjoiYWRtaW4iLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.nAZrMctonBmzL3J_53qOKedsNsjKisf_1hmwX6-k5lA","message":{"Exception":"TypeError","Message":"Argument 3 passed to OC\\AppFramework\\Middleware\\MiddlewareDispatcher::beforeOutput() must be of the type string, bool given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 119","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":119,"function":"beforeOutput","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\CallbackController"},"download",true]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\CallbackController"},"download"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Onlyoffice\\Controller\\CallbackController","download",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"onlyoffice.callback.download"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"onlyoffice.callback.download"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"onlyoffice.callback.download"}]},{"file":"/var/www/html/lib/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/onlyoffice/download"]},{"file":"/var/www/html/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","Line":157,"CustomMessage":"--"},"userAgent":"Go-http-client/1.1","version":"16.0.0.9","id":"5ccaafb1dfd64"}`

Any ideas, what causes the error?

**Comment by jonasgarstick** [comment]
Same problem here if advanced permissions are activated.

**Comment by icewind1991** [comment]
I think this issue is fixed with 4.0.0 but I don't have OnlyOffice setup to verify

**Comment by jesusaristigueta** [comment]
Hello! I'm trying this and having the same issue with NextCloud 16. I'm running the latest OnlyOffice Document Server 5.2. What's the 3.0.0. and 4.0.0 versions referred to?

**Comment by htyangya** [comment]
Same problem by using collabra  if advanced permissions are activated

**Comment by puzich** [comment]
Have you updated to v4.0.0?

**Comment by htyangya** [comment]
> Have you updated to v4.0.0?

No，I used nextcloud 16 and the group   folders v3.0.0，is  the  issue  fixed with 4.0.0？ how to update？

**Comment by htyangya** [comment]
> Have you updated to v4.0.0?

I upgraded to version 4.0 and tried again. The problem was not solved. As long as any group adds a advanced permission rule, the group account cannot open a file by collabora。

**Comment by anzolin-claudio** [comment]
I upgraded to 4.0.1. The problem persists. NC 16 / Group Folders 4.0.1 / OnlyOffice 2.2.10

**Comment by thecube13** [comment]
NC 16 / Group Folders 4.0.2 / OnlyOffice 2.2.10. Promblem persist :(
