### ISSUE TITLE
Group folder quota not effectiv

### ISSUE THREAD

**Issue by Wrumm** [nextcloud/groupfolders#42]
Hello,

I created a new Nextcloud 12.0 instance with group folder 1.1.0 on docker with MariaDB 10.2 as database backend.

I created a user with a Test group and a Test groupfolder for that group. 

When limiting the quota to 50 MB and uploading a file of around 65 MB it gets correctly restricted.
When I increase the quota to 100 MB and upload the 65 MB file, it is working. Bud a second upload of the same (renamed) file also works, also it the sum is then above the quota.

Looking in the groupfolder admin side the mouse over on the quota shows, that the current content of the folder is "0 B", which is also wrong, there are around 130 MB in the folder.

Any ideas?

**Comment by himbeere** [comment]
Same issue here. I'm not able to upload directly to a groupfolder.

`
{"reqId":"6hZ9qZLcKrqKe9JBWhoH","level":4,"time":"2017-07-18T08:30:09+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"user","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Security\/700isok.mp4","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\
`

**Comment by himbeere** [comment]
Setting the quota to "unlimited" resolves the issue for now.

**Comment by himbeere** [comment]
I might add we authenticate with ldap. maybe thats the problem? I have it running without problems on another nextcloud which is not using ldap authentication.

**Comment by Wrumm** [comment]
Hello himbeere,

if I understand you problem correctly, you have the exact opposite problem. 
I can upload the file, but that is the problem. I shouldn't be able to do so, because with the upload I exceed the groupfolder quota limit. 

I think it is best to keep this as two separate issues until analysis my show, that they have the same root cause.

**Comment by yamlfd** [comment]
Not only in-effective. For me it also counts incorrect. in group folder administation it shows 1.1 GB in use, but I know I have uploaded around 9GB of images.

**Comment by huste** [comment]
Could this be related to #98 and #158 or even the same issue?

**Comment by fuco809** [comment]
similar issue here with nextcloud15.0.5 and groupfolder 2.0.4

quota set to e.g. 5MB
user cannot upload files oder move files to the folder if over quota. 
but if i try to copy a file in nextcloud to the folder i get a fail message "Your storage is full, files can not be updated or synced anymore!", but the file still is copied to the groupfolder and the quota has no effect on nextcloud webinterface copy actions.

**Comment by ZeikoFr** [comment]
Hi, this issue seems fixed in nextcloud 20 at least, can anyone confirm ?

**Comment by magix2** [comment]
I still have a similar problem using NextCloud 20.0.6. When generating a group folder and starting to synchronize more than the quota, synchronization stops with the error message: exceeding quota. So far so good, however changing the quote does not help. I still get this message. What helped was to create a new group folder and setting a new limit before exceeding the quota.

**Comment by magix2** [comment]
> I still have a similar problem using NextCloud 20.0.6. When generating a group folder and starting to synchronize more than the quota, synchronization stops with the error message: exceeding quota. So far so good, however changing the quote does not help. I still get this message. What helped was to create a new group folder and setting a new limit before exceeding the quota.

Another thing that might have helped was increasing the limit to unlimited and then waiting some time (one day or so) and the problem was resolved.

**Comment by fschrempf** [comment]
@magix2 This issue is really old and I'm not sure if what you are seeing is really related. Can you please open a new issue if you think there is anything still wrong with this in the latest release? Thanks!

**Comment by fschrempf** [comment]
I will close this as stale/outdated issue. Please report any remaining problems in a new issue and test against the latest release. Thanks!
